### PR TITLE
Update workflows.md structure

### PR DESCRIPTION
**Pull request by supernord**

### CODE REVIEW

**Comment by supernord** [comment]
@georgiesamaha 
a simplified workflow documentation template
thoughts?

**Comment by supernord** [comment]
@FarahZKhan / @SarahBeecroft / @ziadbkh - would be great to get your input here as well 😄

**Comment by SarahBeecroft** [comment]
I think this looks better with simplification. What does "If HPC-HTC is other, specify" mean in the table though?

**Comment by supernord** [comment]
Thanks @SarahBeecroft 
What do you think about removing the table? We could instead suggest types of resource usage information to add?

**Comment by supernord** [comment]
> I think this looks better with simplification. What does "If HPC-HTC is other, specify" mean in the table though?

I think this provided the option to add compute that is not `HPC-HTC` (referring to HPC and cloud at peak facilities), and the `other` might be commercial cloud.

**Comment by SarahBeecroft** [comment]
I think the table works and makes sense. You could just delete that column. I think people will put in 'AWS' or whatever in the HPC/HTC column. I would change that title to "HPC/HTC name e.g. Pawsey Setonix" or something more explicit though.

**Comment by georgiesamaha** [comment]
Looks good! I agree with Sarah, is it suitable to replace HTC-HPC to infrasturcture to be more flexible to those working on other types of systems?

**Comment by supernord** [comment]
We could change it from `HPC / HTC` to `Compute system type (e.g. Pawsey Setonix HPC, AWS)`?

**Comment by SarahBeecroft** [comment]
I think just `Compute system (e.g. Pawsey Setonix HPC, AWS)` i.e. removing 'type' would work?

**Comment by ziadbkh** [comment]
I am not sure if it is captured somewhere else, but I think it is good to have clear details on installation steps and all dependencies, containers and conda environments available for the workflow.

**Review by ziadbkh — APPROVED** [review]

**Comment by supernord** [comment]
@ziadbkh - added `install` and `dependency` headings.
what do you think?

**Comment by supernord** [comment]
if the changes look good, I'll merge this PR later today

**Pull request merged**
